[GLOBAL]
pants_version = "2.11.0"
backend_packages.add = [
    "pants.backend.docker",
    "pants.backend.python",
    "pants.backend.awslambda.python",
    "pants.backend.experimental.python",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
    "src/py/exes/example-exe",
    "src/py/sdks/example-sdk",
]

[python]
enable_resolves = true
interpreter_constraints = [">=3.7.1,<3.8"]
default_resolve = "python-default"
lockfile_generator = "pex"

[python.resolves]
python-default = "3rdparty/python/default.lock"
ide = "3rdparty/python/ide.lock"

# For now this is the only way we have to setup the python repo index in CI. This should be fixed in pants 2.14
#{CI}#[python-repos]
#{CI}#indexes.add = ["https://#{PYPI_USERNAME}#:#{PYPI_PASSWORD}#@steeleye.jfrog.io/steeleye/api/pypi/pypi-local/simple"]

[pytest]
lockfile = "3rdparty/python/pytest.lock"
version = "pytest>=6.2.4,<6.3"
extra_requirements.add = [
  "setuptools"
]
